--DROP USER Drive;


CREATE USER Drive IDENTIFIED BY password DEFAULT TABLESPACE USERS;
GRANT CREATE SESSION TO Drive;
GRANT CONNECT TO Drive;
GRANT resource TO Drive;
GRANT CREATE TABLE TO Drive;
GRANT CREATE VIEW TO Drive;
